### ISSUE TITLE
New maintainer of package

### ISSUE THREAD

**Issue by RobWHickman** [zmeers/ggparliament#3]
Thomas is moving into industry (congrats!) so needs new maintainers for packages
see: https://twitter.com/thosjleeper/status/994135461550534656

**Comment by zmeers** [comment]
I am interested in working on this as well. I currently do a lot of data viz work and electoral systems research at the University of Sydney so it'd be a good fit. I'm primarily working on data viz stuff at the moment so I have time to look after it and expand it as necessary. I'd be keen to get this package on CRAN.

**Comment by leeper** [comment]
Great!! Nice hearing from you both. Here's what I would suggest:

1. I'm going to pass maintainership off to Rob since it looks like there's already quite a bit of useful development [over here](https://github.com/RobWHickman/ggparliament/). I'll do that by adding Rob as a contributor on this repo.
2. Rob - I'd suggest sending a PR against this repo and then merging it in so that this remains the definitive version of the package.
3. If you can then delete your fork, we can transfer the repo over to your account (so that URLs redirect correctly).
4. Then, I'd say you both should coordinate on next steps.

Sound good?

**Comment by RobWHickman** [comment]
yep- bit packed atm but will try to get this done before I go away for the weekend.

Completely agree Zoe- the package has enough potential to be on CRAN so I think its a case of adding all the features that a user might want and probably a fair bit of debugging :p

**Comment by zmeers** [comment]
Yes, that sounds good. Looking forward to working together!

**Comment by leeper** [comment]
Great! So glad to have you both involved!

**Comment by leeper** [comment]
Everything should be transferred over. Make sure you update DESCRIPTION with the new authorship details. I'm going to unwatch this repo but rope me in again if I can be useful on anything.

**Comment by leeper** [comment]
Thanks to you both! Good luck!

**Comment by zmeers** [comment]
@leeper I'm planning to change the DESCRIPTION file soon. Do you want to remain an author for this package (and included on any subsequent papers we write) or are you happy to be taken off the project entirely?

**Comment by leeper** [comment]
So, the way this should work is that my role in DESCRIPTION should "aut" for the package. Rob will be "cre" (slight misnomer - means maintainer) and then you - and anyone else - can take on whatever further "aut" or "ctb" roles you want. I don't need to be an author on any papers, etc. but obviously an acknowledgement or citation to the package itself would be appreciated.
